name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Read SSH key from credentials.py
      id: get_ssh_key
      run: |
        python -c "import credentials; print(credentials.SSH_PRIVATE_KEY)" > ssh_key
        echo "SSH_PRIVATE_KEY=$(cat ssh_key)" >> $GITHUB_ENV

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

    - name: Sync files to server
      run: |
        rsync -avz --delete . vulpo@connection.pandaserver.de:/mybot
