on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: Dateien auf Server übertragen
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH Schlüssel abrufen
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
    - name: Verbinden und pullen
      run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd Vulpo-Discord-Bot && git checkout main && git pull && exit"
    - name: Aufräumen
      run: rm -rf ~/.ssh
